DATA = [
    {
        "Scheme_Code": 148534,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01861",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Banking & PSU Debt Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 12.5063,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Banking and PSU Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148536,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01879",
        "ISIN_Div_Reinvestment": "INF00XX01887",
        "Scheme_Name": "ITI Banking & PSU Debt Fund - Direct Plan - IDCW Option",
        "Net_Asset_Value": 12.5063,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Banking and PSU Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148535,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01838",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Banking & PSU Debt Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 12.2424,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Banking and PSU Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148533,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01846",
        "ISIN_Div_Reinvestment": "INF00XX01853",
        "Scheme_Name": "ITI Banking & PSU Debt Fund - Regular Plan - IDCW Option",
        "Net_Asset_Value": 12.2424,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Banking and PSU Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149030,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BK7",
        "ISIN_Div_Reinvestment": "INF00XX01BG5",
        "Scheme_Name": "ITI Dynamic Bond Fund - Direct Plan - Annually IDCW Option",
        "Net_Asset_Value": 12.2676,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Dynamic Bond",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149029,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BC4",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Dynamic Bond Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 12.2675,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Dynamic Bond",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149023,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BH3",
        "ISIN_Div_Reinvestment": "INF00XX01BD2",
        "Scheme_Name": "ITI Dynamic Bond Fund - Direct Plan - Monthly IDCWOption",
        "Net_Asset_Value": 10.1466,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Dynamic Bond",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149025,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BI1",
        "ISIN_Div_Reinvestment": "INF00XX01BE0",
        "Scheme_Name": "ITI Dynamic Bond Fund - Direct Plan - Quarterly IDCW Option",
        "Net_Asset_Value": 12.2861,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Dynamic Bond",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149027,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BB6",
        "ISIN_Div_Reinvestment": "INF00XX01AX2",
        "Scheme_Name": "ITI Dynamic Bond Fund - Regular Plan - Annually IDCWOption",
        "Net_Asset_Value": 11.862,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Dynamic Bond",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149021,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AT0",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Dynamic Bond Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 11.8619,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Dynamic Bond",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149026,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BA8",
        "ISIN_Div_Reinvestment": "INF00XX01AW4",
        "Scheme_Name": "ITI Dynamic Bond Fund - Regular Plan - Half Yearly IDCW Option",
        "Net_Asset_Value": 11.8638,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Dynamic Bond",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149022,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AY0",
        "ISIN_Div_Reinvestment": "INF00XX01AU8",
        "Scheme_Name": "ITI Dynamic Bond Fund - Regular Plan - Monthly IDCW Option",
        "Net_Asset_Value": 10.117,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Dynamic Bond",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149024,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AZ7",
        "ISIN_Div_Reinvestment": "INF00XX01AV6",
        "Scheme_Name": "ITI Dynamic Bond Fund - Regular Plan - Quarterly IDCW Option",
        "Net_Asset_Value": 11.8628,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Dynamic Bond",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147161,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01366",
        "ISIN_Div_Reinvestment": "INF00XX01333",
        "Scheme_Name": "ITI Liquid Fund - Direct Plan - Annually IDCW Option",
        "Net_Asset_Value": 1299.2882,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Liquid Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147157,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01283",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Liquid Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 1297.9733,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Liquid Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147163,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01358",
        "ISIN_Div_Reinvestment": "INF00XX01325",
        "Scheme_Name": "ITI Liquid Fund - Direct Plan - Monthly IDCW Option",
        "Net_Asset_Value": 1003.3699,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Liquid Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147159,
        "ISIN_Div_Payout_ISIN_Growth": "-",
        "ISIN_Div_Reinvestment": "INF00XX01309",
        "Scheme_Name": "ITI Liquid Fund - Direct Plan - Weekly IDCW Option",
        "Net_Asset_Value": 1002.1051,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Liquid Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147162,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01275",
        "ISIN_Div_Reinvestment": "INF00XX01242",
        "Scheme_Name": "ITI Liquid Fund - Regular Plan - Annually IDCW Option",
        "Net_Asset_Value": 1295.1836,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Liquid Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147155,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01259",
        "ISIN_Div_Reinvestment": "INF00XX01226",
        "Scheme_Name": "ITI Liquid Fund - Regular Plan - Fortnightly Income Distribution cum capital withdrawal option Option",
        "Net_Asset_Value": 1003.3128,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Liquid Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147153,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01192",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Liquid Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 1288.6708,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Liquid Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147156,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01267",
        "ISIN_Div_Reinvestment": "INF00XX01234",
        "Scheme_Name": "ITI Liquid Fund - Regular Plan - Monthly IDCW Option",
        "Net_Asset_Value": 1001.1538,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Liquid Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147164,
        "ISIN_Div_Payout_ISIN_Growth": "-",
        "ISIN_Div_Reinvestment": "INF00XX01218",
        "Scheme_Name": "ITI Liquid Fund - Regular Plan - Weekly IDCW Option",
        "Net_Asset_Value": 1002.0774,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Liquid Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147713,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01564",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Overnight Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 1251.3707,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Overnight Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147717,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01630",
        "ISIN_Div_Reinvestment": "INF00XX01606",
        "Scheme_Name": "ITI Overnight Fund - Direct Plan - Monthly IDCW Option",
        "Net_Asset_Value": 1003.2135,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Overnight Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147715,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01556",
        "ISIN_Div_Reinvestment": "INF00XX01523",
        "Scheme_Name": "ITI Overnight Fund - Regular Plan - Annual IDCW Option",
        "Net_Asset_Value": 1167.5933,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Overnight Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147716,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01531",
        "ISIN_Div_Reinvestment": "INF00XX01507",
        "Scheme_Name": "ITI Overnight Fund - Regular Plan - Fortnightly IDCW Option",
        "Net_Asset_Value": 1003.2386,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Overnight Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147714,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01473",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Overnight Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 1245.1698,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Overnight Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147712,
        "ISIN_Div_Payout_ISIN_Growth": "-",
        "ISIN_Div_Reinvestment": "INF00XX01499",
        "Scheme_Name": "ITI Overnight Fund - Regular Plan - Weekly IDCW Option",
        "Net_Asset_Value": 1001.9772,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Overnight Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148909,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AM5",
        "ISIN_Div_Reinvestment": "INF00XX01AJ1",
        "Scheme_Name": "ITI Ultra Short Duration Fund - Direct Plan - Annually IDCW Option",
        "Net_Asset_Value": 1208.1402,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Ultra Short Duration Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148913,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AE2",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Ultra Short Duration Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 1206.684,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Ultra Short Duration Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148917,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AD4",
        "ISIN_Div_Reinvestment": "INF00XX01AA0",
        "Scheme_Name": "ITI Ultra Short Duration Fund - Regular Plan - Annually IDCW Option",
        "Net_Asset_Value": 1172.8331,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Ultra Short Duration Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148912,
        "ISIN_Div_Payout_ISIN_Growth": "-",
        "ISIN_Div_Reinvestment": "INF00XX01960",
        "Scheme_Name": "ITI Ultra Short Duration Fund - Regular Plan - Daily IDCW Option",
        "Net_Asset_Value": 1001.3457,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Ultra Short Duration Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148911,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AB8",
        "ISIN_Div_Reinvestment": "INF00XX01986",
        "Scheme_Name": "ITI Ultra Short Duration Fund - Regular Plan - Fortnightly IDCW Option",
        "Net_Asset_Value": 1003.1885,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Ultra Short Duration Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148906,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01952",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Ultra Short Duration Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 1172.7992,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Ultra Short Duration Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148914,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AC6",
        "ISIN_Div_Reinvestment": "INF00XX01994",
        "Scheme_Name": "ITI Ultra Short Duration Fund - Regular Plan - Monthly IDCW Option",
        "Net_Asset_Value": 1003.1851,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Ultra Short Duration Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148907,
        "ISIN_Div_Payout_ISIN_Growth": "-",
        "ISIN_Div_Reinvestment": "INF00XX01978",
        "Scheme_Name": "ITI Ultra Short Duration Fund - Regular Plan - Weekly IDCW Option",
        "Net_Asset_Value": 1002.0153,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Debt Scheme - Ultra Short Duration Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147541,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01390",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI ELSS Tax Saver Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 27.4088,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - ELSS",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147542,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01408",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI ELSS Tax Saver Fund - Direct Plan - IDCW Option",
        "Net_Asset_Value": 25.2742,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - ELSS",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147544,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01374",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI ELSS Tax Saver Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 24.8072,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - ELSS",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147543,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01382",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI ELSS Tax Saver Fund - Regular Plan - IDCW Option",
        "Net_Asset_Value": 22.7647,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - ELSS",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 151379,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01CO7",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Flexi Cap Fund- Direct Plan- Growth",
        "Net_Asset_Value": 18.7353,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Flexi Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 151380,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01CP4",
        "ISIN_Div_Reinvestment": "INF00XX01CQ2",
        "Scheme_Name": "ITI Flexi Cap Fund- Direct Plan- IDCW",
        "Net_Asset_Value": 18.7353,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Flexi Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 151377,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01CL3",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Flexi Cap Fund- Regular Plan- Growth",
        "Net_Asset_Value": 18.2036,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Flexi Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 151378,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01CM1",
        "ISIN_Div_Reinvestment": "INF00XX01CN9",
        "Scheme_Name": "ITI Flexi Cap Fund- Regular Plan- IDCW",
        "Net_Asset_Value": 18.2036,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Flexi Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 151777,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01CS8",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Focused Equity Fund - Direct Plan - Growth",
        "Net_Asset_Value": 15.1976,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Focused Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 151776,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01CT6",
        "ISIN_Div_Reinvestment": "INF00XX01CU4",
        "Scheme_Name": "ITI Focused Equity Fund - Direct Plan - IDCW",
        "Net_Asset_Value": 15.1976,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Focused Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 151778,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01CV2",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Focused Equity Fund - Regular Plan - Growth",
        "Net_Asset_Value": 14.8418,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Focused Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 151775,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01CW0",
        "ISIN_Div_Reinvestment": "INF00XX01CR0",
        "Scheme_Name": "ITI Focused Equity Fund - Regular Plan - IDCW",
        "Net_Asset_Value": 14.8418,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Focused Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148353,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01804",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Large Cap Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 19.5073,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Large Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148352,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01812",
        "ISIN_Div_Reinvestment": "INF00XX01820",
        "Scheme_Name": "ITI Large Cap Fund - Direct Plan - IDCW Option",
        "Net_Asset_Value": 19.5073,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Large Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148351,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01770",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Large Cap Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 18.0347,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Large Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148354,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01788",
        "ISIN_Div_Reinvestment": "INF00XX01796",
        "Scheme_Name": "ITI Large Cap Fund - Regular Plan - IDCW Option",
        "Net_Asset_Value": 18.0347,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Large Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148733,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01929",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Mid Cap Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 23.9092,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Mid Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148731,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01937",
        "ISIN_Div_Reinvestment": "INF00XX01945",
        "Scheme_Name": "ITI Mid Cap Fund - Direct Plan - IDCW Option",
        "Net_Asset_Value": 22.9117,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Mid Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148732,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01895",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Mid Cap Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 22.2192,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Mid Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148734,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01903",
        "ISIN_Div_Reinvestment": "INF00XX01911",
        "Scheme_Name": "ITI Mid Cap Fund - Regular Plan - IDCW Option",
        "Net_Asset_Value": 21.2307,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Mid Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147183,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01168",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Multi Cap Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 27.4019,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Multi Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147186,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01176",
        "ISIN_Div_Reinvestment": "INF00XX01184",
        "Scheme_Name": "ITI Multi Cap Fund - Direct Plan - IDCW Option",
        "Net_Asset_Value": 25.2516,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Multi Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147184,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01135",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Multi Cap Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 24.5911,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Multi Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147185,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01143",
        "ISIN_Div_Reinvestment": "INF00XX01150",
        "Scheme_Name": "ITI Multi Cap Fund - Regular Plan - IDCW Option",
        "Net_Asset_Value": 22.5428,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Multi Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149321,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BU6",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Banking and Financial Services Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 14.6297,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Sectoral/ Thematic",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149322,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BV4",
        "ISIN_Div_Reinvestment": "INF00XX01BW2",
        "Scheme_Name": "ITI Banking and Financial Services Fund - Direct Plan - IDCW Option",
        "Net_Asset_Value": 14.6297,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Sectoral/ Thematic",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149323,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BS0",
        "ISIN_Div_Reinvestment": "INF00XX01BT8",
        "Scheme_Name": "ITI Banking and Financial Services Fund - Regular Plan - IDCW Option",
        "Net_Asset_Value": 13.819,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Sectoral/ Thematic",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149324,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BR2",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Banking and Financial Services Fund -Regular Plan - Growth Option",
        "Net_Asset_Value": 13.819,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Sectoral/ Thematic",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149268,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BO9",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Pharma and Healthcare Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 17.7624,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Sectoral/ Thematic",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149271,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BP6",
        "ISIN_Div_Reinvestment": "INF00XX01BQ4",
        "Scheme_Name": "ITI Pharma and Healthcare Fund - Direct Plan - IDCW Option",
        "Net_Asset_Value": 17.7624,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Sectoral/ Thematic",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149270,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BL5",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Pharma and Healthcare Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 16.7416,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Sectoral/ Thematic",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 149269,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BM3",
        "ISIN_Div_Reinvestment": "INF00XX01BN1",
        "Scheme_Name": "ITI Pharma and Healthcare Fund - Regular Plan - IDCW Option",
        "Net_Asset_Value": 16.7416,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Sectoral/ Thematic",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147919,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01747",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Small Cap Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 31.5509,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Small Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147917,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01754",
        "ISIN_Div_Reinvestment": "INF00XX01762",
        "Scheme_Name": "ITI Small Cap Fund - Direct Plan - IDCW Option",
        "Net_Asset_Value": 30.527,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Small Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147920,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01713",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Small Cap Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 28.7864,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Small Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147918,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01721",
        "ISIN_Div_Reinvestment": "INF00XX01739",
        "Scheme_Name": "ITI Small Cap Fund - Regular Plan - IDCW Option",
        "Net_Asset_Value": 27.7714,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Small Cap Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148972,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AQ6",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Value Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 18.8565,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Value Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148970,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AR4",
        "ISIN_Div_Reinvestment": "INF00XX01AS2",
        "Scheme_Name": "ITI Value Fund - Direct Plan - IDCW Option",
        "Net_Asset_Value": 18.8565,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Value Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148973,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AN3",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Value Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 17.6279,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Value Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 148971,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AO1",
        "ISIN_Div_Reinvestment": "INF00XX01AP8",
        "Scheme_Name": "ITI Value Fund - Regular Plan - IDCW Option",
        "Net_Asset_Value": 17.6279,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Equity Scheme - Value Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147617,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01440",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Arbitrage Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 12.7557,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Hybrid Scheme - Arbitrage Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147615,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01457",
        "ISIN_Div_Reinvestment": "INF00XX01465",
        "Scheme_Name": "ITI Arbitrage Fund - Direct Plan - IDCW Option",
        "Net_Asset_Value": 12.7557,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Hybrid Scheme - Arbitrage Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147618,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01416",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Arbitrage Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 12.2853,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Hybrid Scheme - Arbitrage Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147616,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01424",
        "ISIN_Div_Reinvestment": "INF00XX01432",
        "Scheme_Name": "ITI Arbitrage Fund - Regular Plan - IDCW Option",
        "Net_Asset_Value": 12.2853,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Hybrid Scheme - Arbitrage Fund",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147789,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01689",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Balanced Advantage Fund - Direct Plan - Growth Option",
        "Net_Asset_Value": 15.4955,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Hybrid Scheme - Dynamic Asset Allocation or Balanced Advantage",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147788,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01697",
        "ISIN_Div_Reinvestment": "INF00XX01705",
        "Scheme_Name": "ITI Balanced Advantage Fund - Direct Plan - IDCW Option",
        "Net_Asset_Value": 14.6312,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Hybrid Scheme - Dynamic Asset Allocation or Balanced Advantage",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147787,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01655",
        "ISIN_Div_Reinvestment": "-",
        "Scheme_Name": "ITI Balanced Advantage Fund - Regular Plan - Growth Option",
        "Net_Asset_Value": 14.095,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Hybrid Scheme - Dynamic Asset Allocation or Balanced Advantage",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147786,
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01663",
        "ISIN_Div_Reinvestment": "INF00XX01671",
        "Scheme_Name": "ITI Balanced Advantage Fund - Regular Plan - IDCW Option",
        "Net_Asset_Value": 13.237,
        "Date": "09-Sep-2024",
        "Scheme_Type": "Open Ended Schemes",
        "Scheme_Category": "Hybrid Scheme - Dynamic Asset Allocation or Balanced Advantage",
        "Mutual_Fund_Family": "ITI Mutual Fund"
    },
    {
        "Scheme_Code": 147158,
        "Date": "09-Sep-2024",
        "ISIN_Div_Payout_ISIN_Growth": "-",
        "ISIN_Div_Reinvestment": "INF00XX01291",
        "Mutual_Fund_Family": "ITI Mutual Fund",
        "Net_Asset_Value": 1001,
        "Scheme_Category": "Debt Scheme - Liquid Fund",
        "Scheme_Name": "ITI Liquid Fund - Direct Plan - Daily IDCW Option",
        "Scheme_Type": "Open Ended Schemes"
    },
    {
        "Scheme_Code": 147154,
        "Date": "09-Sep-2024",
        "ISIN_Div_Payout_ISIN_Growth": "-",
        "ISIN_Div_Reinvestment": "INF00XX01200",
        "Mutual_Fund_Family": "ITI Mutual Fund",
        "Net_Asset_Value": 1001,
        "Scheme_Category": "Debt Scheme - Liquid Fund",
        "Scheme_Name": "ITI Liquid Fund - Regular Plan - Daily IDCW Option",
        "Scheme_Type": "Open Ended Schemes"
    },
    {
        "Scheme_Code": 147709,
        "Date": "09-Sep-2024",
        "ISIN_Div_Payout_ISIN_Growth": "-",
        "ISIN_Div_Reinvestment": "INF00XX01481",
        "Mutual_Fund_Family": "ITI Mutual Fund",
        "Net_Asset_Value": 1001,
        "Scheme_Category": "Debt Scheme - Overnight Fund",
        "Scheme_Name": "ITI Overnight Fund - Regular Plan - Daily IDCW Option",
        "Scheme_Type": "Open Ended Schemes"
    },
    {
        "Scheme_Code": 147718,
        "Date": "09-Sep-2024",
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01549",
        "ISIN_Div_Reinvestment": "INF00XX01515",
        "Mutual_Fund_Family": "ITI Mutual Fund",
        "Net_Asset_Value": 1002.5,
        "Scheme_Category": "Debt Scheme - Overnight Fund",
        "Scheme_Name": "ITI Overnight Fund - Regular Plan - Monthly IDCW Option",
        "Scheme_Type": "Open Ended Schemes"
    },
    {
        "Scheme_Code": 149028,
        "Date": "09-Sep-2024",
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01BJ9",
        "ISIN_Div_Reinvestment": "INF00XX01BF7",
        "Mutual_Fund_Family": "ITI Mutual Fund",
        "Net_Asset_Value": 10.1904,
        "Scheme_Category": "Debt Scheme - Dynamic Bond",
        "Scheme_Name": "ITI Dynamic Bond Fund - Direct Plan - Half Yearly IDCW Option",
        "Scheme_Type": "Open Ended Schemes"
    },
    {
        "Scheme_Code": 148916,
        "Date": "09-Sep-2024",
        "ISIN_Div_Payout_ISIN_Growth": "INF00XX01AL7",
        "ISIN_Div_Reinvestment": "INF00XX01AI3",
        "Mutual_Fund_Family": "ITI Mutual Fund",
        "Net_Asset_Value": 1002.126,
        "Scheme_Category": "Debt Scheme - Ultra Short Duration Fund",
        "Scheme_Name": "ITI Ultra Short Duration Fund - Direct Plan - Monthly IDCW Option",
        "Scheme_Type": "Open Ended Schemes"
    }
]
